# Generated by Django 5.0.6 on 2024-07-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qurilish_tashkiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='Qurilish_binosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maydoni', models.IntegerField()),
                ('qavat', models.IntegerField()),
                ('parkovka', models.BooleanField()),
                ('bolalar_maydonchasi', models.BooleanField()),
                ('lift', models.BooleanField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.hudud')),
                ('qurilish_tashkiloti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.qurilish_tashkiloti')),
            ],
        ),
    ]
